name: CI Implementation
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "5.0"

      - name: Run something here
        run: node test.js

      - name: run frontend
        run: |
          cd contact-fox-frontend
          npm i
          npm start  &

      - name: run contact-fox-backend
        run: |
          cd contact-fox-backend
          npm i
          npm start  &

      - name: To run test
        run: |
          cd  tests
          npm i
          cd features2
          cd tests
          npm run test:e2e features
